---
title: "Austin Area Sustainability Indicators - Shiny Dashboard"
description: |
  
categories:
  - Shiny
  - Data Visualization 
author:
  - name: Ethan Tenison
    url: https://twitter.com/ethantenison
date: 01-29-2022
output:
  distill::distill_article:
    self_contained: false
    code_folding: yes
    toc: yes
    toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# About 

<br>
<font size="5">
A little background first, the [Austin Area Sustainability Indicators]("http://www.austinindicators.org/") project (A2SI), an initiative at the University of Texas at Austin, aims is to measure the quality of life, sustainability trends, and serve as the foundation to address challenges in Central Texas. Indicators describe context, identify trends, and translate data into points that are easier to communicate. These indicators span air quality, population demographics, health, mobility, economy, and the environment.

Creating this dashboard was a collaborative effort between A2SI, the City of Austin Office of Sustainability, Dell Medical School, and the Capital Area Region of Governments. The main issue we were trying to solve was were to allocate resources to mitigate the effects of bad air quality, but to even start on that problem you need good air quality data! Which really doesn't exists. That's where Microsoft comes in. They're planning to place high quality air sensors throughout the city, and this app was developed help with that decision making process. 





